### ISSUE TITLE
Normalizing procedure creates a big object 

### ISSUE THREAD

**Issue by MASHUOA** [kuwisdelu/Cardinal#27]
Dear package author,
I found the normalizing procedure creates a big object which is around 100 times of the original image data:
size in the byte, mz shows the number of features.
do you have any ideas?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admgguo484/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admgguo484/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ORG | original
-- | --
NR | normalize
SS | smoothSignal
RB | reduceBaseline
PP | peakPick
PA | peakAlign

</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admgguo484/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admgguo484/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

native_size | native_mz | resolution | type
-- | -- | -- | --
2882664 | 2186 | 800 | ORG
5421408 | 2186 | 800 | NR
2061416 | 2186 | 800 | SS_RB_PP
2082456 | 63 | 800 | SS_RB_PP_PA
5463864 | 2186 | 800 | SS_RB_PP_NR
3005088 | 17489 | 100 | ORG
30151056 | 17489 | 100 | NR
2964864 | 17489 | 100 | SS_RB_PP
2869184 | 776 | 100 | SS_RB_PP_PA
30193512 | 17489 | 100 | SS_RB_PP_NR
4264224 | 174881 | 10 | ORG
284496528 | 174881 | 10 | NR
4301536 | 174881 | 10 | SS_RB_PP
2948200 | 961 | 10 | SS_RB_PP_PA
284538984 | 174881 | 10 | SS_RB_PP_NR

</body>

</html>

**Comment by Bear-Baolin** [comment]
I have also meet this question. Have you solved it?
