### ISSUE TITLE
reading larger than memory files in cardinal 2.0.2

### ISSUE THREAD

**Issue by catalintucureanu** [kuwisdelu/Cardinal#3]
I'm trying to read some very large (>200Gb) datasets in cardinal using attach.only=TRUE. While cardinal 1.10 would ignore the option since the data are PROCESSED (exported from Bruker) and cause R to consume all available 128GB RAM available before crashing, Cardinal 2.0.2 is trying to allocate memory and instantly fails with: 
Error in .local(x, ..., na.rm) : 
  'Calloc' could not allocate memory (18446744071698911232 of 8 bytes)

my environment is:

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /home/catalintucureanu/Downloads/R-3.5.1/lib/libRblas.so
LAPACK: /home/catalintucureanu/Downloads/R-3.5.1/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.iso885915    LC_NUMERIC=C               
 [3] LC_TIME=en_US.UTF-8         LC_COLLATE=en_US.iso885915 
 [5] LC_MONETARY=en_GB.UTF-8     LC_MESSAGES=en_US.iso885915
 [7] LC_PAPER=en_GB.UTF-8        LC_NAME=C                  
 [9] LC_ADDRESS=C                LC_TELEPHONE=C             
[11] LC_MEASUREMENT=en_GB.UTF-8  LC_IDENTIFICATION=C        

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] Cardinal_2.0.2      ProtGenerics_1.14.0 S4Vectors_0.20.1   
[4] EBImage_4.24.0      BiocParallel_1.16.2 BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         compiler_3.5.1     pillar_1.3.0       BiocManager_1.30.4
 [5] matter_1.8.2       bindr_0.1.1        bitops_1.0-6       tools_3.5.1       
 [9] digest_0.6.18      tibble_1.4.2       lattice_0.20-38    pkgconfig_2.0.2   
[13] png_0.1-7          rlang_0.3.0.1      Matrix_1.2-15      DBI_1.0.0         
[17] biglm_0.9-1        bindrcpp_0.2.2     dplyr_0.7.8        fftwtools_0.9-8   
[21] htmlwidgets_1.3    tidyselect_0.2.5   locfit_1.5-9.1     grid_3.5.1        
[25] glue_1.3.0         Biobase_2.42.0     R6_2.3.0           jpeg_0.1-8        
[29] tcltk_3.5.1        sp_1.3-1           irlba_2.3.2        purrr_0.2.5       
[33] magrittr_1.5       MASS_7.3-51.1      htmltools_0.3.6    abind_1.4-5       
[37] assertthat_0.2.0   tiff_0.1-5         signal_0.7-6       RCurl_1.95-4.11   
[41] crayon_1.3.4

**Comment by kuwisdelu** [comment]
Can you provide the output of `traceback()` immediately after the error occurs?

**Comment by catalintucureanu** [comment]
Thanks! It works as It's supposed to when I specify mass.range. I'm attaching the output of traceback() below:

6: .Call("C_getRange", x, na.rm, PACKAGE = "matter")
5: .local(x, ..., na.rm)
4: range(new("matter_vec", data = new("atoms", natoms = 40200L, 
       ngroups = 1L, group_id = new("drle", values = 1L, lengths = 40200L, 
           deltas = 0L), source_id = new("drle", values = 1L, lengths = 40200L, 
           deltas = 0L), datamode = new("drle", values = 10L, lengths = 40200L, 
           deltas = 0L), offset = new("drle", values = 16, lengths = 40200L, 
           deltas = 6037504), extent = new("drle", values = 377344, 
           lengths = 40200L, deltas = 0), index_offset = new("drle", 
           values = c(0, -2147125248, -2147163136, -2147201024, 
           -2147238912), lengths = c(5692L, 11382L, 11382L, 11382L, 
           362L), deltas = c(377344, 377344, 377344, 377344, 377344
           )), index_extent = new("drle", values = c(377344, -2147125248, 
       -2147163136, -2147201024, -2147238912), lengths = c(5691L, 
       11382L, 11382L, 11382L, 363L), deltas = c(377344, 377344, 
       377344, 377344, 377344)), c(natoms = 1, ngroups = 1, group_id = 1, 
   source_id = NA, datamode = 10, offset = 0, extent = 0, index_extent = 0, 
   index_offset = 0)), datamode = 4L, paths = "/home/catalintucureanu/Dropbox/2018_core/date/brydney50u.ibd", 
       filemode = "rb", chunksize = 100000000L, length = 15169228800, 
       dim = NULL, names = NULL, dimnames = NULL, ops = NULL), na.rm = FALSE)
3: range(new("matter_vec", data = new("atoms", natoms = 40200L, 
       ngroups = 1L, group_id = new("drle", values = 1L, lengths = 40200L, 
           deltas = 0L), source_id = new("drle", values = 1L, lengths = 40200L, 
           deltas = 0L), datamode = new("drle", values = 10L, lengths = 40200L, 
           deltas = 0L), offset = new("drle", values = 16, lengths = 40200L, 
           deltas = 6037504), extent = new("drle", values = 377344, 
           lengths = 40200L, deltas = 0), index_offset = new("drle", 
           values = c(0, -2147125248, -2147163136, -2147201024, 
           -2147238912), lengths = c(5692L, 11382L, 11382L, 11382L, 
           362L), deltas = c(377344, 377344, 377344, 377344, 377344
           )), index_extent = new("drle", values = c(377344, -2147125248, 
       -2147163136, -2147201024, -2147238912), lengths = c(5691L, 
       11382L, 11382L, 11382L, 363L), deltas = c(377344, 377344, 
       377344, 377344, 377344)), c(natoms = 1, ngroups = 1, group_id = 1, 
   source_id = NA, datamode = 10, offset = 0, extent = 0, index_extent = 0, 
   index_offset = 0)), datamode = 4L, paths = "/home/catalintucureanu/Dropbox/2018_core/date/brydney50u.ibd", 
       filemode = "rb", chunksize = 100000000L, length = 15169228800, 
       dim = NULL, names = NULL, dimnames = NULL, ops = NULL), na.rm = FALSE)
2: .readIbd(ibdpath, info, outclass = outclass, attach.only = attach.only, 
       mass.range = mass.range, resolution = resolution, units = units)
1: readImzML("date/brydney50u", attach.only = TRUE)

**Comment by catalintucureanu** [comment]
with data on disk and mass.range specified I do get a spectrum (not a good one, since it's a background pixel, but it looks ok otherwise)

**Comment by kuwisdelu** [comment]
OK, in that case, you can keep using the `mass.range` parameter as a short-term fix. (It's a good idea to provide it anyway if you already know it, as otherwise the mass range must be read from the data, which can take a long time.)

The error is basically that the number of pixels is stored as a 32-bit integer, which is fairly reasonable for now, but when the m/z arrays are coerced to an on-disk vector to more easily read the mass range, there is an overflow in the byte offsets.

I will try to apply a fix as soon as I can.

**Comment by catalintucureanu** [comment]
Thanks for the help! Just noticed mass.range can be used to truncate the data (not remap as I initially presumed, and thus, avoided), so there is no need to give an exact range (which is never exactly what I set up in the spectrometer :)

**Comment by kuwisdelu** [comment]
Yes. The underlying data and their m/z values remain the same. The `mass.range` just sets what range of data is represented to you.

**Comment by kuwisdelu** [comment]
This should now (hopefully) be fixed by package `matter` versions 1.8.3 and 1.9.7.

(May take a few days to propagate to Bioconductor.)

**Comment by catalintucureanu** [comment]
Thanks! Will test tomorrow from source (it's currently midnight in my timezone, going home)
