### ISSUE TITLE
Unable to preprocess MSI data with lasted Cardinal

### ISSUE THREAD

**Issue by YonghuiDong** [kuwisdelu/Cardinal#31]
Dear Kylie, 

I have a MSI data acquired with a SIMS instrument. 

I was able to analyze the data using Cardinal v2.14.  But I cannot process the same data with the latest Cardinal version(v3.5.0).

(1) when I read the MSI data, I got the following warning:

> In CardinalIO::parseImzML(xmlpath, ibd = TRUE) : 
   couldn't determine checksum from imzML file

(2) When I try to plot some ion images, I got the following error:

> Error in h(simpleError(msg, call)) :  
   error in evaluating the argument 'x' in selecting a method for function 'as.list': subscript out of bounds

(3) When I try to preprocess the data, I got the follow error:

> Error: BiocParallel errors
  1 remote errors, element index: 1
  19 unevaluated and other errors
  first remote error:
Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'as.matrix': subscript out of bounds

I can read the same data and plot ion images using MsiReader software. The data itself should be fine.

I could share you with my MSI data if needed.

Thanks for your help.

Best regards,

Yonghui

**Comment by kuwisdelu** [comment]
If you can share your data or a subset of it, I can take a look when I’m able.

**Comment by YonghuiDong** [comment]
Dear Kylie,

Thanks a lot for your kind help.

I have updated the MSI data to METASPACE, you can download the data here: https://metaspace2020.eu/dataset/2023-11-30_12h29m55s

Best regards,
Yonghui

**Comment by kuwisdelu** [comment]
Reopen if issue persists in 3.6

**Comment by kuwisdelu** [comment]
Fixed by matter 2.6.1
