### ISSUE TITLE
Typo in README for installation instructions

### ISSUE THREAD

**Issue by sslakkimsetty** [kuwisdelu/Cardinal#33]
Hi Kylie, 

I noticed a typo in the README file. For installation of Cardinal through remotes package, the correct command is `remotes::install_github("kuwisdelu/Cardinal")`. It is showing `remotes::github_install("kuwisdelu/Cardinal")` currently. 

Many thanks! 
-- Sai

**Comment by kuwisdelu** [comment]
Fixed by https://github.com/kuwisdelu/Cardinal/commit/ee6aecb4ad98beee7c6c7c7c824c714106cc0f89
