### ISSUE TITLE
Documentation for cardinal

### ISSUE THREAD

**Issue by QQhuan** [kuwisdelu/Cardinal#35]
Where can I get the user documentation？The url of user guide https://bioconductor.org/packages/release/bioc/vignettes/Cardinal/inst/doc/Cardinal-3-guide.html was invalid. 
![image](https://github.com/kuwisdelu/Cardinal/assets/49111981/84898433-0c07-44ca-ae47-6c7a2012d3af)
Waiting for it to be fixed.

**Comment by kuwisdelu** [comment]
Thanks for letting me know to update the website. Those are just convenience links to Bioconductor where the web versions of the vignettes have always been hosted:

https://bioconductor.org/packages/3.19/bioc/html/Cardinal.html
https://bioconductor.org/packages/3.19/data/experiment/html/CardinalWorkflows.html

They are also included with the package via `browseVignettes("Cardinal")` or, e.g., `vignette("Cardinal3-guide")` as suggested in the package startup message when you load Cardinal via `library()`.
