### ISSUE TITLE
Can I rotate the image (plot)

### ISSUE THREAD

**Issue by qingnanl** [kuwisdelu/Cardinal#46]
Thanks for the great work here!
I wonder if there is any way to rotate the visualization of the data (output of function 'image'), such as flipping vertically or rotating 90 degrees. Sorry, I am not very familiar with the format of the visualization output. Many thanks!

Qingnan

**Comment by kuwisdelu** [comment]
For the image only, the easiest way to do this would be to change the image formula.

The default for ?Cardinal::image is `intensity ~ x * y`. You could pass the formula as `intensity ~ y * x` to flip the x/y axis, for example.

If you want to apply spatial transformations to the dataset itself, you can transform the coordinates in `coord(obj)` as you like.
