### ISSUE TITLE
normalization is not processed

### ISSUE THREAD

**Issue by DennisJakob** [kuwisdelu/Cardinal#7]
Hi,
I want to normalize imzml data with `msi_TIC <- process(normalize(msi,method = "tic"))` but it takes for ages. After all it stops with 35 warnings:
> In serialize(data, node$con) :
  'package:stats' may not be available when loading

Do you know where the problem is there?

**Comment by kuwisdelu** [comment]
If you are only getting warnings, does it complete and return a reasonable dataset?

The warning must be coming from the parallel worker sessions, but if there are no errors, it may not be affecting anything.

Depending on the size of your dataset, the overhead of parallelization may not be worth it.

You can try using `register(SerialParam())` during your session or passing `BPPARAM=SerialParam()` to `process()` and see if running things serially is better.

**Comment by DennisJakob** [comment]
No it does not return a dataset. 

I tried running it serially and it works fine! Thanks for the suggestion.
