### ISSUE TITLE
Feature request: adding interactive plot and MSI image

### ISSUE THREAD

**Issue by YonghuiDong** [kuwisdelu/Cardinal#8]
Hi Kylie,

Thanks for this great package. 

Have you considered including interactive plots in Cardinal 2 (maybe 3)?  The users could benefit a lot from them, i.e. to better optimise Cardinal parameters by interactively(precisely) inspect the m/z values in mass spectrum plot.  

Dong

**Comment by kuwisdelu** [comment]
We are working on a second package that will provide interactive visualization for Cardinal objects. If development goes well, we are planning for it to be ready for submission for the Fall release of Bioconductor 3.10.
